version: "3.7"
services:
  axon-server:
    image: axoniq/axonserver
    environment:
      - AXONSERVER_EVENTSTORE=/eventstore
      - AXONSERVER_CONTROLDB=/controldb
      - AXONSERVER_HOSTNAME=axon-server
      - AXONSERVER_NAME=axon-server
    volumes:
      - axon-server-eventstore-stapi:/eventstore
      - axon-server-controldb-stapi:/controldb
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - stapi

volumes:
  axon-server-eventstore-stapi:
  axon-server-controldb-stapi:

networks:
  stapi:
