version: "3.7"
services:
  app:
    build:
      dockerfile: ./docker/java/Dockerfile
      context: .
    entrypoint: ["/app/mvnw", "spring-boot:run"]
    environment:
      - FRONTEND_CLIENT=localhost:3000
    volumes:
      - .:/app
      - ./storage/java-cache:/home/java/.m2
    ports:
      - "8080:8080"
    depends_on:
      - axon-server
    networks:
      - stapi

  axon-server:
    image: axoniq/axonserver
    environment:
      - AXONSERVER_EVENTSTORE=/eventstore
      - AXONSERVER_CONTROLDB=/controldb
      - AXONSERVER_HOSTNAME=axon-server
      - AXONSERVER_NAME=axon-server
    volumes:
      - axon-server-eventstore-stapi:/eventstore
      - axon-server-controldb-stapi:/controldb
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - stapi

volumes:
  axon-server-eventstore-stapi:
  axon-server-controldb-stapi:

networks:
  stapi:
